# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          command: docker image pull snyk/snyk:node-12
          name: Get docker image
      - setup_remote_docker
      - run:
          command: docker run --rm -it --env SNYK_TOKEN -v ./:/app snyk/snyk:node-12 code test || true
          name: Run code scan
      - run:
          command: snyk test || true
          name: Run open source scan
      - run:
          command: snyk container test node:12.18.4-buster || true
          name: Test docker image
      - run:
          command: snyk iac test || true
          name: Test IAC files