name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Change to frontend directory
        run: cd ./frontend

      - name: Check directory
        run: cd ./frontend

      - name: Snyk Monitor
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor