name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Change to frontend directory
        run: |
          pwd
          cd frontend
          pwd
      
      - name: Do a Scan with Snyk Node Image
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        command:
          test