name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Change to frontend directory
        run: cd ./frontend

      - name: Check directory
        run: pwd
      
      - name: Get the snyk node image
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Do A Snyk Scan
        run: |
          cd frontend |
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
