name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
      - uses: actions/checkout@main
      
      - name: Snyk Monitor
      - uses: snyk/actions/setup@master
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
